#!/usr/bin/env python
import sys
from twython import Twython
import os
 
CONSUMER_KEY = 'YOUR TWITTER APP CONSUMER KEY'
CONSUMER_SECRET = 'YOUR TWITTER APP CONSUMER SECRET'
ACCESS_KEY = 'YOUR TWITTER APP ACCESS KEY'
ACCESS_SECRET = 'YOUR TWITTER APP ACCESS SECRET'
 
api = Twython(CONSUMER_KEY,CONSUMER_SECRET,ACCESS_KEY,ACCESS_SECRET)
 
cmd = '/opt/vc/bin/vcgencmd measure_temp'
line = os.popen(cmd).readline().strip()
temp = line.split('=')[1].split("'")[0]
api.update_status(status='The temperature of the Raspberry is '+temp+' C #RaspBerry')
